#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='/home/kevin/Pictures/wallpapers/wallhaven-1p6l3v.png'

swaybg --output '*' --mode fill --image "$WALLPAPER"
