# vim:fileencoding=utf-8:ft=conf
font_family     MesloLGM Nerd Font Mono
italic_font      auto
bold_font        auto
bold_italic_font auto
font_size        12.0
# background       #000000
background_opacity 0.85
cursor_shape     block
cursor_blink_interval     0.5
cursor_stop_blinking_after 15.0
scrollback_lines 9000
scrollback_pager less +G -R
wheel_scroll_multiplier 5.0
click_interval 0.5
select_by_word_characters :@-./_~?&=%+#
mouse_hide_wait 0.0
enabled_layouts *
repaint_delay    10
input_delay 3
visual_bell_duration 0.0
enable_audio_bell no
open_url_modifiers ctrl+shift
open_url_with default
term xterm-kitty
window_border_width 0
window_margin_width 15

map ctrl+shift+s        paste_from_selection
map shift+insert        paste_from_selection
map ctrl+shift+up        scroll_line_up
map ctrl+shift+down      scroll_line_down
map ctrl+shift+k         scroll_line_up
map ctrl+shift+j         scroll_line_down
map ctrl+shift+page_up   scroll_page_up
map ctrl+shift+page_down scroll_page_down
map ctrl+shift+home      scroll_home
map ctrl+shift+end       scroll_end
map ctrl+shift+h         show_scrollback
map ctrl+shift+up      increase_font_size
map ctrl+shift+down    decrease_font_size
map ctrl+shift+backspace restore_font_size

#hide_window_decorations yes
confirm_os_window_close 0
allow_remote_control no 

