return {
  "folke/trouble.nvim",
  cmd = { "Trouble" },
  keys = {
    { "<leader>e",  "<cmd>Trouble diagnostics<CR>",      desc = "Diagnostics (Trouble)" },
    { "<leader>ew", "<cmd>Trouble diagnostics<CR>",      desc = "Workspace Diagnostics (Trouble)" },
    { "<leader>ed", "<cmd>Trouble diagnostics filter.buf=0<CR>", desc = "Document Diagnostics (Trouble)" },
    { "<leader>eq", "<cmd>Trouble qflist<CR>",           desc = "Quickfix List (Trouble)" },
    { "<leader>el", "<cmd>Trouble loclist<CR>",          desc = "Location List (Trouble)" },
    { "<leader>es", "<cmd>Trouble lsp_document_symbols<CR>", desc = "Document Symbols (Trouble)" },
    { "<leader>eS", "<cmd>Trouble lsp<CR>",              desc = "LSP references/defs (Trouble)" },
  },
  opts = {
    auto_close = false,
    auto_open = false,
    auto_preview = true,
    auto_refresh = true,
    auto_jump = false,
    focus = false,
    follow = true,
    indent_guides = true,
    max_items = 200,
    multiline = true,
    pinned = false,
    warn_no_results = true,
    open_no_results = false,
    win = { position = "bottom", size = 10 },
    preview = { type = "main", scratch = true },
    keys = {
      ["?"] = "help",
      r = "refresh",
      R = "toggle_refresh",
      q = "close",
      o = "jump_close",
      ["<esc>"] = "cancel",
      ["<cr>"] = "jump",
      ["<2-leftmouse>"] = "jump",
      ["<c-s>"] = "jump_split",
      ["<c-v>"] = "jump_vsplit",
      ["}"] = "next",
      ["]]"] = "next",
      ["{"] = "prev",
      ["[["] = "prev",
      dd = "delete",
      d = { action = "delete", mode = "v" },
      i = "inspect",
      p = "preview",
      P = "toggle_preview",
      zo = "fold_open",
      zO = "fold_open_recursive",
      zc = "fold_close",
      zC = "fold_close_recursive",
      za = { action = "fold_toggle", mode = "v" },
      zA = { action = "fold_toggle_recursive", mode = "v" },
    },
  },
}

