# TMUX Configuration File

# General settings
set -g status-interval 5
set -g mouse on
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -q -g status-utf8 on
setw -q -g utf8 on
set -g update-environment "DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY LANG LC_ALL LC_CTYPE"


# Enable true color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc"

# Base status bar styling
set -g status-position bottom
set -g status-justify left
set -g status-style "bg=#1e1e1e,fg=#7a8478"

# Left side
set -g status-left-length 50
set -g status-left "#[fg=#73caf6,bg=#1e1e1e]#[fg=#1a1a1a,bg=#73caf6,bold] #S #[fg=#73caf6,bg=#313244]#[fg=#cdd6f4,bg=#313244] #I:#P #[fg=#313244,bg=#1e1e1e] "

# Inactive windows
setw -g window-status-format "#[fg=#585b70,bg=#1e1e1e] #I:#W "

# Active window/pane
setw -g window-status-current-format "#[fg=#73caf6,bg=#1e1e1e,bold] #I:#W* "

# Spacing between window items
setw -g window-status-separator " "

# Right side
set -g status-right-length 80
set -g status-right "#[fg=#a6e3a1,bg=#1e1e1e]d#[fg=#f38ba8]rwx#[fg=#74c7ec]r-x#[fg=#f38ba8]r-x #[fg=#313244,bg=#1e1e1e]#[fg=#cdd6f4,bg=#313244] %H:%M #[fg=#73caf6,bg=#313244]#[fg=#1a1a1a,bg=#73caf6,bold] %Y-%m-%d #[fg=#73caf6,bg=#1e1e1e]"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager
run '~/.config/tmux/plugins/tpm/tpm'
source-file -q "$XDG_CONFIG_HOME/tmux/themes/noctalia.conf"
