# Shell variables
# Generated by 'wal'
wallpaper="/home/kevin/Pictures/wallpapers/gpygdd.png"

# Special
background='#040404'
foreground='#c0c0c0'
cursor='#c0c0c0'

# Colors
color0='#040404'
color1='#585663'
color2='#916C70'
color3='#375E8E'
color4='#5F7190'
color5='#718DAF'
color6='#9999A7'
color7='#c0c0c0'
color8='#645151'
color9='#585663'
color10='#916C70'
color11='#375E8E'
color12='#5F7190'
color13='#718DAF'
color14='#9999A7'
color15='#c0c0c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
