# Shell variables
# Generated by 'wal'
wallpaper="/home/kevin/Pictures/wallpapers/wallhaven-1p6l3v.png"

# Special
background='#0A0E0F'
foreground='#c1c2c3'
cursor='#c1c2c3'

# Colors
color0='#0A0E0F'
color1='#336268'
color2='#4A575A'
color3='#4A6C72'
color4='#B83334'
color5='#4E7B85'
color6='#5D939E'
color7='#c1c2c3'
color8='#57656a'
color9='#336268'
color10='#4A575A'
color11='#4A6C72'
color12='#B83334'
color13='#4E7B85'
color14='#5D939E'
color15='#c1c2c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
