$wallpaper = /home/kevin/.waypaper_engine/images/wallhaven-1p6l3v.png
$background = 121414
$foreground = e3e2e2
$color0 = 383939
$color1 = 93aeb3
$color2 = 9ab4b8
$color3 = a2b9bd
$color4 = a9bfc2
$color5 = b1c4c8
$color6 = b8cacd
$color7 = c7c6c6
$color8 = 464747
$color9 = a9cdd5
$color10 = b2d2d9
$color11 = bad7dd
$color12 = c3dce2
$color13 = cbe1e6
$color14 = d4e6ea
$color15 = e3e2e2

$primary = b8cacd
$secondary = bfc8ca
$tertiary = b1cbd1
$surface = #121414
$surface_bright = 383939
$error = ff5945
