source=~/.config/hypr/colors.conf

# BACKGROUND
background {
    monitor =
    path = $wallpaper #path to background image
    blur_passes = 3
    blur_size = 3
    contrast = 1.0
    brightness = 0.5
    vibrancy = 0.0
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
    hide_cursor = true
}

# INPUT FIELD
input-field {
    monitor =
    size = 256, 48
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.5 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = 0x00000000
    inner_color = 0xbaffffff 
    font_color = 0xff000000
    fail_color = 0xff$error
    check_color = 0xff$tertiary
    capslock_color = 0xff$secondary
    fade_on_empty = true 
    font_family = MesloLGL Nerd Font
    placeholder_text =  #text for input password
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 5
    shadow_boost = 0.5
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
    text_align = center
    color = 0xff$foreground
    font_size = 48
    font_family = MesloLGL Nerd Font Bold
    position = 0, 350 
    halign = center
    valign = center 
    shadow_passes = 1
    shadow_size = 5
    shadow_boost = 0.5
}

# PICTURE
#image {
#  path = .face.icon
#  size = 150
#  position = 0, 50
#  halign = center
#  valign = center
#  border_size = 0 
#  border_color = 0xaa$background
#  shadow_passes = 1
#  shadow_size = 5
#  shadow_boost = 0.5
#}
