#? Config file for btop

save_config_on_exit = False

#* Appearance
color_theme = "noctalia"
theme_background = false
truecolor = true
rounded_corners = true
vim_keys = false
graph_symbol = "braille"

#* Layout
shown_boxes = "cpu mem net proc"
update_ms = 2000
cpu_bottom = false
mem_below_net = true

#* CPU
check_temp = true
show_coretemp = true
temp_scale = "celsius"
cpu_single_graph = false
show_uptime = true
base_10_sizes = false
clock_format = "%X"

#* Processes
proc_sorting = "cpu lazy"
proc_tree = false
proc_reversed = false
proc_per_core = true
proc_mem_bytes = true
