# wallust
# https://explosion-mental.codeberg.page/wallust/
#
# If comming from v2: https://explosion-mental.codeberg.page/wallust/v3.html#wallusttoml

# Global section - values below can be overwritten by command line flags

# How the image is parse, in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "resized"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed
color_space = "lchmixed"

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
palette = "harddark"

# Ensures a "readable contrast" (OPTIONAL, disabled by default)
# Should only be enabled when you notice an unreadable contrast frequently happening
# with your images. The reference color for the contrast is the background color.
check_contrast = true 

# Difference between similar colors, used by the colorspace:
#  1          Not perceptible by human eyes.
#  1 - 2      Perceptible through close observation.
#  2 - 10     Perceptible at a glance.
#  11 - 49    Colors are more similar than opposite
#  100        Colors are exact opposite
#threshold = 11 

# Alpha value for templating, by default 100 (no other use whatsoever)
#alpha = 80

[templates]
colors.template='colors'
colors.target='~/.cache/wallust/colors'

pywal.template='pywal-colors'
pywal.target = '~/.cache/wal/colors'

hypr.template = 'colors-hypr.conf'
hypr.target = '~/.config/hypr/colors.conf'

rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/colors.rasi'

waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/colors.css'

kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/colors.conf'

pywalfox.template = 'colors.json'
pywalfox.target = '~/.cache/wal/colors.json'

nvchad.template='colors-nvchad.lua'
nvchad.target='~/.local/share/nvim/lazy/base46/lua/base46/themes/chadwal.lua'

#light46.template='base46-light.lua'
#light46.target='~/.cache/wallust/base46-light.lua'
