cursor #e3e2e2
cursor_text_color #c7c6c6

foreground            #e3e2e2
background            #121414
selection_foreground  #293234
selection_background  #bfc8ca
url_color             #b8cacd

# black
color0   #121414
color8   #464747

# red
color1   #ff8678
color9   #ffb4ab

# green
color2   #91b6be
color10   #b1cbd1

# yellow
color3   #b2d2d9
color11   #d4e6ea

# blue
color4   #ff8678
color12   #ffb4ab

# magenta
color5   #91b6be
color13   #b1cbd1

# cyan
color6   #b2d2d9
color14   #d4e6ea

# white
color7   #c7c6c6
color15   #e3e2e2
