# matugen colors
include ~/.config/kitty/colors.conf

# fonts
font_family          MesloLGM Nerd Font
bold_font            MesloLGM Nerd Font
italic_font          MesloLGM Nerd Font
bold_italic_font     MesloLGM Nerd Font
font_size 11
force_ltr no

# cursor
cursor_shape beam
cursor_beam_thickness 1.5
cursor_shape_unfocused hollow 
shell_integration no-cursor
scrollback_lines 20000
url_style straight
copy_on_select clipboard
window_padding_width 5
allow_remote_control yes
confirm_os_window_close 0

# background
background_opacity 0.9 
# background_blur 0
dynamic_background_opacity no
